# Example tests with REST Client (VSCode Extension)

@url = http://localhost:5004/api
@json = content-type: application/json
@key = x-api-key: rrVaLR4kE4vKPw5N2LpzBoREBzx4cumv

###

GET {{url}}/dispatches?gs=5285f0c2a7b5474ca05735ab765311dc&since=2022-05-11T00:38:08%2b00:00
{{key}}

###

POST {{url}}/dispatch
{{json}}
{{key}}

{
    "trigger": "ls -l",
    "targetGroup": "5285f0c2a7b5474ca05735ab765311dc",
    "targetName": "jamtest"
}

###

PUT {{url}}/dispatch
{{json}}

{
    "id": 1,
    "name": "dispatch"
}

###

DELETE {{url}}/dispatch/448355b31547460ea95746ea1beca164
{{key}}
