# Example tests with REST Client (VSCode Extension)

@url = http://localhost:5004/api
@json = content-type: application/json
@auth = Authorization: Bearer {{login.response.body.access_token}}
@apikey = x-api-key: dev1234

###
POST {{url}}/gamespace
{{apikey}}
{{json}}

{
    "resourceId": "e4b2d5a9-e0db-4562-9366-cbc0f69c95aa",
    "startGamespace": false,
    "players": [
        {
            "subjectId": "8dc8ef5a-52a1-4608-8dae-794fb5a359f8",
            "subjectName": "Admin"
        }
    ]
}
###
POST {{url}}/gamespace/aea6b6488dea4bd2828cb40dca73b4a8/start
{{apikey}}

###
GET {{url}}/workspaces?filter=play
{{auth}}

###
GET {{url}}/workspace/059ce94f-63d3-47bc-bd4a-773ceb41fbfd
{{auth}}

###
GET {{url}}/workspace/059ce94f-63d3-47bc-bd4a-773ceb41fbfd/templates
{{auth}}


###
PUT {{url}}/workspace
{{auth}}
{{json}}

{
  "id": "059ce94f-63d3-47bc-bd4a-773ceb41fbfd",
  "name": "Workspace Title",
  "description": "Workspace Description",
  "author": "Tester Jam",
  "audience": null,
  "templateLimit": 4,
  "templateScope": "jam"
}

###
DELETE {{url}}/workspace/cf4d217717b5454ca893b3ee8469c796
{{auth}}

###
GET {{url}}/templates?filter=published
{{auth}}

###
# Obtain access token from IdentityServer
# @name login
#
POST http://localhost:5000/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=dev-client
&client_secret=dev-secret
&scope=openid dev-api
&username=admin@this.ws
&password=321ChangeMe!

###
# Configure OIDC resources with IdentityServer
#
POST http://localhost:5000/api/resource/devimport
Content-Type: application/json

{
    "Apis": [
        {
            "Name": "dev-api",
            "Scopes": "dev-api",
            "UserClaims": ""
        }
    ],
    "Clients": [
        {
            "Id": "dev-client",
            "Secret": "dev-secret",
            "GrantType": "client_credentials password",
            "Scopes": " dev-api dev-api-admin openid profile"
        },
        {
            "Id": "dev-code",
            "GrantType": "authorization_code",
            "Scopes": "dev-api openid profile email org",
            "RedirectUrl": [
                "http://localhost:4200/oidc",
                "http://localhost:4201/oidc",
                "http://localhost:4202/oidc",
                "http://localhost:4200/assets/oidc-silent.html",
                "http://localhost:4201/assets/oidc-silent.html",
                "http://localhost:4202/assets/oidc-silent.html",
                "http://localhost:5004/api/oauth2-redirect.html"
            ]

        }
    ]
}
