name: CI

on:
  release:
    types: ["published"]

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build & Publish
    uses: cmu-sei/Crucible-Github-Actions/.github/workflows/docker-build.yaml@docker-v1.1
    with:
      imageName: cmusei/topomojo-api
      tagName: ${{ github.event.release.tag_name }}
      versionMode: csproj
      versionFiles: |
        src/TopoMojo.Api/TopoMojo.Api.csproj
      buildArgs: |
        commit=${{ github.sha }}

    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
